#!/usr/bin/env python3
# plan/0140 step 1 / call/0023 D2: the per-fingerprint SPECIALIZER.
#
# Reads a packed program (program-split.json) and emits a straight-line CUDA
# kernel body that replaces core/interp.cu's `for i` dispatch loop: each
# instruction becomes a DIRECT call to its op_* device function (kind resolved
# at codegen time -> the 27-way switch and the kind-validity guard vanish),
# with the block range as a compile-time literal and OP_BOUNDARY as a bare
# bar.cross(). Spike 3 measured the reclaimed dispatch tax at ~0.76 ms/pass
# (94% of the interp loop). The op_* functions, the persistent spine (doorbell/
# epoch/error), weight streaming, and the sync protocol are reused VERBATIM;
# only the dispatch loop is specialized. The interpreter remains the
# fingerprint-miss fallback (call/0023).
#
# Emits an .inc included by a thin generated kernel wrapper (specialize also
# emits the wrapper). Output is deterministic from program-split.json (same
# input -> byte-identical .inc), so the parity gate is "generated kernel ==
# interpreter on the same program" (KL=0, 32/32 greedy, state byte-compare).
import json, sys, argparse

# kind -> device op function (mirrors k0/ops/registry.cuh MK_WIRED_OPS exactly).
OP_FN = {
    "OP_RMSNORM": "op_rmsnorm", "OP_RESIDUAL_ADD": "op_residual_add",
    "OP_EMBED_LOOKUP": "op_embed_lookup", "OP_LOGITS_EMIT": "op_logits_emit",
    "OP_STATE_LOAD": "op_state_load", "OP_CONV_SHIFT_CONCAT": "op_conv_shift_concat",
    "OP_SSM_CONV_SILU": "op_ssm_conv_silu", "OP_QK_L2NORM": "op_qk_l2norm",
    "OP_GDN_GATES": "op_gdn_gates", "OP_GDN_STEP": "op_gdn_step",
    "OP_GATED_RMSNORM": "op_gated_rmsnorm", "OP_STATE_STORE": "op_state_store",
    "OP_QUANT_Q8_1": "op_quant_q8_1", "OP_MMVQ_Q4_0": "op_mmvq_q4_0",
    "OP_MMVQ_Q4_0_FUSED": "op_mmvq_q4_0_fused", "OP_MMVQ_AR16": "op_mmvq_ar16",
    "OP_GEMV_F16": "op_gemv_f16", "OP_HEAD_GEMV_F16": "op_head_gemv_f16",
    "OP_QK_NORM_ROPE": "op_qk_norm_rope", "OP_KV_APPEND": "op_kv_append",
    "OP_FATTN_DECODE": "op_fattn_decode", "OP_FATTN_REDUCE": "op_fattn_reduce",
    "OP_ATTN_GATE": "op_attn_gate", "OP_XCHG_PUSH": "op_xchg_push",
    "OP_XCHG_REDUCE": "op_xchg_reduce",
}

def emit(prog_path, out_path):
    d = json.load(open(prog_path))
    ins = d["instructions"]
    # instruction index in the UPLOADED array = position among non... no: the
    # host uploads ALL instructions (incl boundaries) as the Instr[] array, so
    # prog[i] indexes the same array the interpreter walks. Preserve i.
    lines = []
    lines.append("// GENERATED by k0/specialize.py from %s -- DO NOT EDIT." % prog_path)
    lines.append("// Straight-line dispatch body (call/0023 D2). Included inside the")
    lines.append("// pass loop of the generated kernel; `prog`, `smem`, `bid`, `epoch`,")
    lines.append("// `bar` are in scope (same names as core/interp.cu).")
    n_boundary = n_op = 0
    for i, insn in enumerate(ins):
        k = insn["kind"]
        if k == "OP_BOUNDARY":
            lines.append("    bar.cross(epoch);")
            n_boundary += 1
            continue
        if k == "OP_NOP":
            continue
        fn = OP_FN.get(k)
        if fn is None:
            sys.exit("unwired kind %s at instr %d (add to OP_FN / registry.cuh)" % (k, i))
        lo, hi = insn["block_lo"], insn["block_hi"]
        # block range as compile-time literals; the guard is folded, no switch.
        if lo == 0 and hi >= 72:
            lines.append("    %s(program[%d], mk_smem);" % (fn, i))          # whole grid
        elif lo == 0:
            lines.append("    if (blockIdx.x < %d) %s(program[%d], mk_smem);"  # unsigned: no >=0
                         % (hi, fn, i))
        else:
            lines.append("    if (blockIdx.x >= %d && blockIdx.x < %d) %s(program[%d], mk_smem);"
                         % (lo, hi, fn, i))
        n_op += 1
    body = "\n".join(lines) + "\n"
    open(out_path, "w").write(body)
    kinds = sorted({i["kind"] for i in ins if i["kind"] not in ("OP_BOUNDARY", "OP_NOP")})
    return len(ins), n_op, n_boundary, kinds

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("program", nargs="?", default="program-split.json")
    ap.add_argument("-o", "--out", default="mk_specialized_body.inc")
    a = ap.parse_args()
    total, nop, nb, kinds = emit(a.program, a.out)
    print("specialized %s: %d instrs -> %d op calls + %d boundaries -> %s" %
          (a.program, total, nop, nb, a.out))
    print("op kinds wired:", len(kinds), "of", len(OP_FN))
    unwired = [k for k in kinds if k not in OP_FN]
    if unwired:
        print("UNWIRED:", unwired); sys.exit(1)
    print("all kinds present in registry map. dispatch switch + kind-guard eliminated by construction.")
